'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import type {
  AudioLayers,
  AudioVolumes,
  PlaybackPosition,
  PlaybackSpeed,
  PlaybackState,
} from '@waqup/shared/types';
import { DEFAULT_VOLUMES } from '@waqup/shared/types';
import { logError } from '@waqup/shared/utils';

interface UseWebAudioPlayerResult {
  state: PlaybackState;
  position: PlaybackPosition;
  volumes: AudioVolumes;
  speed: PlaybackSpeed;
  analyserNode: AnalyserNode | null;
  /** Exposed for useBinauralEngine — oscillators should connect to this node */
  audioContext: AudioContext | null;
  /** Exposed for useBinauralEngine — controls binaural layer gain */
  binauralGain: GainNode | null;
  play: () => void;
  pause: () => void;
  seek: (positionMs: number) => void;
  setVolumes: (v: Partial<AudioVolumes>) => void;
  setSpeed: (s: PlaybackSpeed) => void;
  isReady: boolean;
}

/**
 * Web Audio API player for the three-layer audio system.
 *
 * Layers:
 *   Voice   — main narration, runs once, drives the analyser for visualization
 *   Ambient — looping atmosphere soundscape (loaded from file)
 *   Binaural — generated by useBinauralEngine (oscillators connect to binauralGain)
 *   Master  — overall gain bus
 *
 * Architecture notes:
 *   - Raw ArrayBuffers are fetched eagerly so loading starts immediately.
 *   - The AudioContext is created lazily on the first play() call (user gesture).
 *     This satisfies iOS Safari's requirement that AudioContext.resume() be called
 *     within a user-gesture handler stack.
 *   - Position tracking uses setInterval(250ms) rather than 60fps RAF to reduce
 *     CPU on mobile while keeping the progress bar smooth enough.
 *   - Ambient source is explicitly stopped when the voice track ends so it doesn't
 *     loop indefinitely after playback completes.
 */
export function useWebAudioPlayer(
  layers: AudioLayers,
  initialVolumes?: Partial<AudioVolumes>,
): UseWebAudioPlayerResult {
  const [state, setState] = useState<PlaybackState>('idle');
  const [position, setPosition] = useState<PlaybackPosition>({ positionMs: 0, durationMs: 0 });
  const [volumes, setVolumesState] = useState<AudioVolumes>({ ...DEFAULT_VOLUMES, ...initialVolumes });
  const [speed, setSpeedState] = useState<PlaybackSpeed>(1.0);
  const [analyserNode, setAnalyserNode] = useState<AnalyserNode | null>(null);
  const [audioContext, setAudioContext] = useState<AudioContext | null>(null);
  const [binauralGain, setBinauralGain] = useState<GainNode | null>(null);
  const [isReady, setIsReady] = useState(false);

  // Audio graph refs
  const ctxRef = useRef<AudioContext | null>(null);
  const voiceSourceRef = useRef<AudioBufferSourceNode | null>(null);
  const ambientSourceRef = useRef<AudioBufferSourceNode | null>(null);
  const voiceGainRef = useRef<GainNode | null>(null);
  const ambientGainRef = useRef<GainNode | null>(null);
  const binauralGainRef = useRef<GainNode | null>(null);
  const masterGainRef = useRef<GainNode | null>(null);
  const analyserRef = useRef<AnalyserNode | null>(null);

  // Raw ArrayBuffers fetched eagerly — decoded after AudioContext is created
  const voiceArrayBufRef = useRef<ArrayBuffer | null>(null);
  const ambientArrayBufRef = useRef<ArrayBuffer | null>(null);

  // Decoded AudioBuffers — available once graph is built
  const voiceBufferRef = useRef<AudioBuffer | null>(null);
  const ambientBufferRef = useRef<AudioBuffer | null>(null);

  // Playback state refs
  const startTimeRef = useRef<number>(0);
  const pausedAtRef = useRef<number>(0);
  const tickRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const speedRef = useRef<PlaybackSpeed>(1.0);
  const volumesRef = useRef<AudioVolumes>({ ...DEFAULT_VOLUMES, ...initialVolumes });

  // Keep speedRef and volumesRef in sync with state
  useEffect(() => { speedRef.current = speed; }, [speed]);
  useEffect(() => { volumesRef.current = volumes; }, [volumes]);

  // ── Stop the position ticker ───────────────────────────────────────────────
  const stopTick = useCallback(() => {
    if (tickRef.current !== null) {
      clearInterval(tickRef.current);
      tickRef.current = null;
    }
  }, []);

  // ── Stop all running audio sources ────────────────────────────────────────
  const stopSources = useCallback(() => {
    try { voiceSourceRef.current?.stop(); } catch { /* already stopped */ }
    try { ambientSourceRef.current?.stop(); } catch { /* already stopped */ }
    voiceSourceRef.current = null;
    ambientSourceRef.current = null;
  }, []);

  // ── Build the Web Audio graph (called lazily on first play) ───────────────
  const buildGraph = useCallback(async (): Promise<boolean> => {
    if (ctxRef.current) return true; // Already built

    try {
      const ctx = new AudioContext();
      ctxRef.current = ctx;

      // ── Gain nodes ──────────────────────────────────────────────────────────
      const masterGain = ctx.createGain();
      const voiceGain = ctx.createGain();
      const ambientGain = ctx.createGain();
      const binGain = ctx.createGain();
      const analyser = ctx.createAnalyser();
      analyser.fftSize = 256;

      masterGain.gain.value = volumesRef.current.master / 100;
      voiceGain.gain.value = volumesRef.current.voice / 100;
      ambientGain.gain.value = volumesRef.current.ambient / 100;
      binGain.gain.value = volumesRef.current.binaural / 100;

      // ── Signal routing ───────────────────────────────────────────────────────
      // Voice → analyser → master  (analyser drives waveform visualization)
      voiceGain.connect(analyser);
      analyser.connect(masterGain);
      // Ambient + binaural bypass analyser, connect directly to master
      ambientGain.connect(masterGain);
      binGain.connect(masterGain);
      masterGain.connect(ctx.destination);

      masterGainRef.current = masterGain;
      voiceGainRef.current = voiceGain;
      ambientGainRef.current = ambientGain;
      binauralGainRef.current = binGain;
      analyserRef.current = analyser;

      // ── Decode raw buffers ────────────────────────────────────────────────────
      if (voiceArrayBufRef.current) {
        voiceBufferRef.current = await ctx.decodeAudioData(voiceArrayBufRef.current.slice(0));
      }
      if (ambientArrayBufRef.current) {
        try {
          ambientBufferRef.current = await ctx.decodeAudioData(ambientArrayBufRef.current.slice(0));
        } catch (ambErr) {
          console.warn('[useWebAudioPlayer] ambient decode failed (non-fatal):', ambErr);
        }
      }

      // Expose nodes for useBinauralEngine and waveform visualization
      setAnalyserNode(analyser);
      setAudioContext(ctx);
      setBinauralGain(binGain);

      return true;
    } catch (e) {
      logError('WebAudioPlayer.buildGraph', e);
      return false;
    }
  }, []);

  // ── Fetch raw audio data eagerly on URL change ─────────────────────────────
  useEffect(() => {
    if (!layers.voiceUrl) return;
    let cancelled = false;

    const fetch_ = async () => {
      setState('loading');
      try {
        const voiceRes = await fetch(layers.voiceUrl as string);
        const voiceArr = await voiceRes.arrayBuffer();
        if (cancelled) return;
        voiceArrayBufRef.current = voiceArr;

        // Peek duration without a full AudioContext — create a temp one just for decode.
        // This happens in the background, not a user gesture, so it may be suspended
        // on iOS Safari. We only need it for duration display; actual playback uses
        // the lazily-built graph created on the first play() call.
        const tempCtx = new AudioContext();
        const tempBuf = await tempCtx.decodeAudioData(voiceArr.slice(0));
        void tempCtx.close();
        if (cancelled) return;

        setPosition({ positionMs: 0, durationMs: tempBuf.duration * 1000 });

        if (layers.ambientUrl) {
          try {
            const ambRes = await fetch(layers.ambientUrl);
            ambientArrayBufRef.current = await ambRes.arrayBuffer();
          } catch (ambErr) {
            console.warn('[useWebAudioPlayer] ambient fetch failed (non-fatal):', ambErr);
          }
        }

        if (!cancelled) {
          setIsReady(true);
          setState('paused');
        }
      } catch (e) {
        logError('WebAudioPlayer.fetch', e);
        if (!cancelled) setState('error');
      }
    };

    void fetch_();

    return () => {
      cancelled = true;
      stopTick();
      stopSources();
      // Reset exposed AudioContext nodes so useBinauralEngine stops oscillators
      setAudioContext(null);
      setBinauralGain(null);
      setAnalyserNode(null);
      void ctxRef.current?.close();
      ctxRef.current = null;
      voiceBufferRef.current = null;
      ambientBufferRef.current = null;
      voiceArrayBufRef.current = null;
      ambientArrayBufRef.current = null;
      setIsReady(false);
      setState('idle');
      pausedAtRef.current = 0;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [layers.voiceUrl, layers.ambientUrl]);

  // ── Volume sync ────────────────────────────────────────────────────────────
  useEffect(() => {
    const ctx = ctxRef.current;
    const t = ctx?.currentTime ?? 0;
    // Use setTargetAtTime for smooth gain changes (avoids clicks/pops)
    masterGainRef.current?.gain.setTargetAtTime(volumes.master / 100, t, 0.01);
    voiceGainRef.current?.gain.setTargetAtTime(volumes.voice / 100, t, 0.01);
    ambientGainRef.current?.gain.setTargetAtTime(volumes.ambient / 100, t, 0.01);
    binauralGainRef.current?.gain.setTargetAtTime(volumes.binaural / 100, t, 0.01);
  }, [volumes]);

  // ── Controls ──────────────────────────────────────────────────────────────
  const play = useCallback(() => {
    const vArrayBuf = voiceArrayBufRef.current;
    if (!vArrayBuf) return;

    // Build the graph lazily on first play (user gesture) for iOS Safari compat.
    // If the graph already exists, buildGraph() returns immediately.
    void buildGraph().then((ok) => {
      if (!ok) return;

      const ctx = ctxRef.current;
      const vBuf = voiceBufferRef.current;
      if (!ctx || !vBuf) return;

      // ctx.resume() MUST be awaited before starting sources on iOS Safari.
      void ctx.resume().then(() => {
        const vs = ctx.createBufferSource();
        vs.buffer = vBuf;
        vs.playbackRate.value = speedRef.current;
        vs.connect(voiceGainRef.current!);
        voiceSourceRef.current = vs;
        vs.start(0, pausedAtRef.current);

        // When voice track ends, stop ambient and move to 'ended' state
        vs.onended = () => {
          if (voiceSourceRef.current !== vs) return; // stale callback after seek/pause
          try { ambientSourceRef.current?.stop(); } catch { /* ok */ }
          ambientSourceRef.current = null;
          voiceSourceRef.current = null;
          stopTick();
          setState('ended');
        };

        if (ambientBufferRef.current) {
          const as = ctx.createBufferSource();
          as.buffer = ambientBufferRef.current;
          as.loop = true;
          as.playbackRate.value = speedRef.current;
          as.connect(ambientGainRef.current!);
          ambientSourceRef.current = as;
          as.start(0, pausedAtRef.current % ambientBufferRef.current.duration);
        }

        startTimeRef.current = ctx.currentTime;
        setState('playing');

        // Position tick at 250ms — sufficient for a progress bar, saves CPU on mobile
        stopTick();
        tickRef.current = setInterval(() => {
          const c = ctxRef.current;
          if (!c) return;
          const elapsed = c.currentTime - startTimeRef.current + pausedAtRef.current;
          const dur = voiceBufferRef.current?.duration ?? 0;
          setPosition({ positionMs: Math.min(elapsed * 1000, dur * 1000), durationMs: dur * 1000 });
        }, 250);
      });
    });
  }, [buildGraph, stopTick]);

  const pause = useCallback(() => {
    const ctx = ctxRef.current;
    if (!ctx) return;
    pausedAtRef.current += ctx.currentTime - startTimeRef.current;
    stopSources();
    void ctx.suspend();
    stopTick();
    setState('paused');
  }, [stopSources, stopTick]);

  const seek = useCallback((positionMs: number) => {
    const ctx = ctxRef.current;
    const vBuf = voiceBufferRef.current;
    if (!ctx || !vBuf) return;

    const wasPlaying = state === 'playing';
    if (wasPlaying) {
      stopSources();
      stopTick();
    }
    pausedAtRef.current = positionMs / 1000;
    setPosition((prev) => ({ ...prev, positionMs }));

    if (wasPlaying) {
      void ctx.resume().then(() => {
        const vs = ctx.createBufferSource();
        vs.buffer = vBuf;
        vs.playbackRate.value = speedRef.current;
        vs.connect(voiceGainRef.current!);
        voiceSourceRef.current = vs;
        vs.start(0, pausedAtRef.current);

        vs.onended = () => {
          if (voiceSourceRef.current !== vs) return;
          try { ambientSourceRef.current?.stop(); } catch { /* ok */ }
          ambientSourceRef.current = null;
          voiceSourceRef.current = null;
          stopTick();
          setState('ended');
        };

        if (ambientBufferRef.current) {
          const as = ctx.createBufferSource();
          as.buffer = ambientBufferRef.current;
          as.loop = true;
          as.playbackRate.value = speedRef.current;
          as.connect(ambientGainRef.current!);
          ambientSourceRef.current = as;
          as.start(0, pausedAtRef.current % ambientBufferRef.current.duration);
        }

        startTimeRef.current = ctx.currentTime;

        tickRef.current = setInterval(() => {
          const c = ctxRef.current;
          if (!c) return;
          const elapsed = c.currentTime - startTimeRef.current + pausedAtRef.current;
          const dur = voiceBufferRef.current?.duration ?? 0;
          setPosition({ positionMs: Math.min(elapsed * 1000, dur * 1000), durationMs: dur * 1000 });
        }, 250);
      });
    }
  }, [state, stopSources, stopTick]);

  const setVolumes = useCallback((v: Partial<AudioVolumes>) => {
    setVolumesState((prev) => ({ ...prev, ...v }));
  }, []);

  const setSpeed = useCallback((s: PlaybackSpeed) => {
    setSpeedState(s);
    speedRef.current = s;
    if (voiceSourceRef.current) voiceSourceRef.current.playbackRate.value = s;
    if (ambientSourceRef.current) ambientSourceRef.current.playbackRate.value = s;
  }, []);

  return {
    state,
    position,
    volumes,
    speed,
    analyserNode,
    audioContext,
    binauralGain,
    play,
    pause,
    seek,
    setVolumes,
    setSpeed,
    isReady,
  };
}
